[package]
name = "financing-service"
version = "2.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.15.0"
serde = { version = "1.0.229", features =["derive"] }
toml = "1.1.4"
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
chrono = "0.4.45"
hex = "0.4.3"
async-mutex = "1.4.1"
async-trait = "0.1.92"
http = "1.5.0"
chain-gang = { version = "0.8.0", git = "https://github.com/nchain-innovation/chain-gang.git", rev = "793e37d4da5cfd8cacfcbf8f635c37ab3b410de9", features = ["interface"] }
log = { version = "0.4.34", features = ["max_level_trace", "release_max_level_warn"] }
opentelemetry = { version = "0.32", features = ["trace"] }
opentelemetry-otlp = { version = "0.32", features = ["grpc-tonic", "trace"] }
opentelemetry_sdk = { version = "0.32", features = ["trace"] }
tracing = "0.1"
tracing-actix-web = { version = "0.7", features = ["opentelemetry_0_32"] }
tracing-log = "0.2"
tracing-opentelemetry = "0.33"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
actix-governor = "0.10.0"

[dev-dependencies]
actix-http = "3"
