# Aerospike database configuration file.

# This stanza must come first.
service {
	user root
	group root
	pidfile /var/run/aerospike/asd.pid
	service-threads 2
	proto-fd-max 15000
        cluster-name test
}

logging {

	# Log file must be an absolute path.
	file /var/log/aerospike/aerospike.log {
		context any info
	}

	# Send log messages to stdout
	console {
		context any info 
	}
}

network {
	service {
		address eth0
		port 3000

		# Uncomment the following to set the `access-address` parameter to the
		# IP address of the Docker host. This will the allow the server to correctly
		# publish the address which applications and other nodes in the cluster to
		# use when addressing this node.
		# access-address <IPADDR>
	}

	heartbeat {
		address eth0
		# mesh is used for environments that do not support multicast
		mode mesh
		port 3002

		# use asinfo -v 'tip:host=<ADDR>;port=3002' to inform cluster of
		# other mesh nodes

		interval 150
		timeout 10
	}

	fabric {
		address eth0
		port 3001
	}

	info {
		port 3003
	}
}

namespace bsv {
    write-commit-level-override master
   	replication-factor 1
   	default-ttl 24h # 5 days, use 0 to never expire/evict.
   	nsup-period 1800
   	stop-writes-sys-memory-pct 97
   	storage-engine memory {
   		data-size 1G
   	}
}

#namespace btc {
#	write-commit-level-override master
#   	replication-factor 1
#   	default-ttl 24h # 5 days, use 0 to never expire/evict.
#   	nsup-period 1800
#   	stop-writes-sys-memory-pct 97
#   	storage-engine memory {
#   		data-size 2G
#   	}
#}
