@startuml
title Financing Service Use Cases
left to right direction

actor Client as C
actor Admin as A

package "Financing Service" {
    C --> (Request Transaction Fund)
    C --> (Request Multiple Transaction Funds)
    C --> (Get Balance)

    A --> (Top-up Balance)
    A --> (Get Status)
}

@enduml