@startuml
title Financing Service Use Cases
left to right direction

actor Client as C
actor Admin as A

package "Financing Service" {
    C --> (Get Status) 
    C --> (Request Transaction Fund)
    C --> (Get Address)
    C --> (Get Balance)

    A --> (Add Client)
    A --> (Delete Client)
}

package "Blockchain" {
    A --> (Top-up Balance)
}

@enduml